# Put these settings into config/credentials.yml.enc
secret_key_base: some_hash
redis_queue_uri: redis://127.0.0.1:6379

sidekiq_user: sidekiq
sidekiq_password: some_password

shopify_app:
  name: "My Shopify App"
  api_key: some_api_key
  secret: some_secret
  scopes:
    - "some_scope"
    - "another_scope"
  webhook_topics:
    - "some_topic"
    - "another_topic"

development:
  host: https://some.ngrok.io/
  new_relic_license_key: some_key
  sentry_dsn: some_dsn
  mix_panel_token: some_token
test:
  host: https://some.ngrok.io/
  new_relic_license_key: some_key
  sentry_dsn: some_dsn
  mix_panel_token: some_token
production:
  host: https://some.host.io/
  new_relic_license_key: some_key
  sentry_dsn: some_dsn
  mix_panel_token: some_token
